name: 'Extract data from project card event'

description: 'Extracts the necessary data from the project card event'

inputs:
  token:
    description: 'The token'
    required: true
  project_card_id:
    description: 'The project card id'
    required: true
  project_url:
    description: 'The project url'
    required: true
  column_id:
    description: 'The column id'
    required: true
  organization_name:
    description: 'The organization name'
    required: true
  repository_name:
    description: 'The repository name'
    required: true

outputs:
  issue_id:
    description: 'The issue id'
  all_column_names:
    description: 'All the columns name'
  column_name:
    description: 'The column name'

runs:
  using: 'node12'
  main: 'dist/index.js'
