name: Generate changelog
description: Uses lerna-changelog to generate the changelog from a tag to another

inputs:
  from:
    description: Old tag
    required: true
  to:
    description: New tag
    required: true

outputs:
  changelog:
    description: The new changelog, formatted as a JSON string

runs:
  using: node12
  main: index.js
