name: Update changelog
description: Updates the CHANGELOG.md file with the contents provided as input

inputs:
  changelog:
    description: The new changelog
    required: true

runs:
  using: node12
  main: index.js
