on:
  project_card:
    types: [moved, created]

name: Project Card Moved or Created

jobs:
  triage:
    name: label card when moved or created
    runs-on: ubuntu-latest
    steps:

      # Output: issue_id, all_column_names, column_name
      - uses: paretogroup/github-actions/extract-data-from-project-card-event@master
        id: extract_data
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          project_card_id: ${{ github.event.project_card.id }}
          project_url: ${{ github.event.project_card.project_url }}
          column_id: ${{ github.event.project_card.column_id }}
          organization_name: ${{ github.event.repository.owner.login}}
          repository_name: ${{ github.event.repository.name }}

      - uses: paretogroup/github-actions/update-column-labels@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_id: ${{ steps.extract_data.outputs.issue_id }}
          all_column_names: ${{ steps.extract_data.outputs.issue_id }}
          column_name: ${{ steps.extract_data.outputs.column_name }}
          organization_name: ${{ github.event.repository.owner.login}}
          repository_name: ${{ github.event.repository.name }}
