on:
  project_card:
    types: [moved, created]

name: Project Card Moved or Created

jobs:
  triage:
    name: label card when moved or created
    runs-on: ubuntu-latest
    steps:

      # Output: issue_id
      - uses: paretogroup/github-actions/extract-issue-from-project-card@master
        id: extract_issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          project_card_id: ${{ github.event.project_card.id }}
          organization_name: ${{ github.event.repository.owner.login}}
          repository_name: ${{ github.event.repository.name }}

      # Output: column_name
      - uses: paretogroup/github-actions/get-column-name-from-column-id@master
        id: get_column_name
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          column_id: ${{ github.event.project_card.column_id }}

      - uses: paretogroup/github-actions/remove-column-labels-from-issue@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_id: ${{ steps.extract_issue.outputs.issue_id }}
          organization_name: ${{ github.event.repository.owner.login}}
          repository_name: ${{ github.event.repository.name }}

      - uses: paretogroup/github-actions/add-label-to-issue@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_id: ${{ steps.extract_issue.outputs.issue_id }}
          organization_name: ${{ github.event.repository.owner.login}}
          repository_name: ${{ github.event.repository.name }}
          label: ${{ steps.get_column_name.outputs.column_name }}
